<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="RACD-002157" name="Tests.LoginTest" tests="8" failures="3" timestamp="04 Jul 2019 12:38:48 GMT" time="20.018" errors="0">
  <testcase name="verifyLoginPageTitleTest" time="5.498" classname="Tests.LoginTest"/>
  <testcase name="verifyHomePageTitleTest" time="3.060" classname="Tests.LoginTest"/>
  <testcase name="verifyContactPageTitleTest" time="10.786" classname="Tests.LoginTest"/>
  <testcase name="verifyUserNameTest" time="0.341" classname="Tests.LoginTest"/>
  <testcase name="verifySearchContactsTest" time="0.004" classname="Tests.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Assert failed due to mismatch of Hello and hello] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Assert failed due to mismatch of Hello and hello] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Tests.LoginTest.verifySearchContactsTest(LoginTest.java:149)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at Tests.TestRunnerClassForAllure.main(TestRunnerClassForAllure.java:19)
]]>
    </failure>
  </testcase> <!-- verifySearchContactsTest -->
  <testcase name="verifyImportsTest" time="0.002" classname="Tests.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Assert failed due to mismatch of Dheeraj and dheeraj] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Assert failed due to mismatch of Dheeraj and dheeraj] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Tests.LoginTest.verifyImportsTest(LoginTest.java:172)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at Tests.TestRunnerClassForAllure.main(TestRunnerClassForAllure.java:19)
]]>
    </failure>
  </testcase> <!-- verifyImportsTest -->
  <testcase name="verifyCreateCompanyTest" time="0.154" classname="Tests.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Assert failed due to mismatch of Motor and Motors] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Assert failed due to mismatch of Motor and Motors] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Tests.LoginTest.verifyCreateCompanyTest(LoginTest.java:194)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at Tests.TestRunnerClassForAllure.main(TestRunnerClassForAllure.java:19)
]]>
    </failure>
  </testcase> <!-- verifyCreateCompanyTest -->
  <testcase name="verifyCreateDashboardTest" time="0.173" classname="Tests.LoginTest">
    <skipped/>
  </testcase> <!-- verifyCreateDashboardTest -->
</testsuite> <!-- Tests.LoginTest -->
